### ISSUE TITLE
remove globus endpoint and directory when submission expires 

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwasdepo-deposition-service#108]
When submissions expire after ? number of days, send a DELETE request to the sumstats service globus endpoint to remove the endpoint and clear the contents.

endpoint:
`gwas-ss-service:8000/v1/sum-stats/globus/<entryUUID>`
method:
`DELETE`
example:
```
curl -i -H "Content-Type: application/json" -X DELETE "gwas-ss-service:8000/v1/sum-stats/globus/5205c641-db40-4cc1-93c0-1bbb8c82178a"
HTTP/1.1 202 ACCEPTED
Server: gunicorn/19.9.0
Date: Mon, 19 Apr 2021 13:51:17 GMT
Connection: keep-alive
Content-Type: application/json
Content-Length: 53

{"unique_id":"5205c641-db40-4cc1-93c0-1bbb8c82178a"}
```
The above request will deactivate the globus endpoint associated with the entry uuid `5205c641-db40-4cc1-93c0-1bbb8c82178a` and remove the directory (recursively).

Just a note that the `<entryUUID>` is the same one that is provided by the depo app to the sumstats service when the globus endpoint is created via the `gwas-ss-service:8000/v1/sum-stats/globus/mkdir` endpoint

Any questions, please ask

**Comment by ala-ebi** [comment]
Done, part of StalledSubmissionsCheckTask which archives INACTIVE or STARTED submissions that been in this status for 30 days. Task is scheduled to run everyday. Also created an API to create the folder and reassign the id to the submission if the user requests to reopen it.

POST /v1/submissions/{submissionId}/globus
{
  "email: "user's globus email"
}

**Comment by ala-ebi** [comment]
@ala-ebi we should take care of old submissions too.
