### ISSUE TITLE
Link to file with accessions is incorrect

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwasdepo-deposition-service#11]
In the email titled "GWAS Catalog submission for some_pmid", the link in the text "Following submission the accession ID(s) for your submission will be available to download from this link." is incorrect.

When uploading a file from localhost instance of the Depo UI, the link in the email goes to:
http://193.62.54.159/gwas/deposition/submission/5eda3d7b93a31d0001018b08/study-envelopes

**Comment by tudorgroza** [comment]
What part of the URL is wrong?

**Comment by twhetzel** [comment]
The end bit with "study-envelopes". I gather you are linking back to the submission page where the user would then click the button to download the accession file.

**Comment by tudorgroza** [comment]
Not really - I believe the instructions were to add directly the download link in the email ... I need to check.

**Comment by twhetzel** [comment]
Using Mail on a Mac, the link does not download a file for me and just opens the Depo app at the URL.

**Comment by tudorgroza** [comment]
Ok - unfortunately, I can't make it link directly to the file, since there will be a need to authenticate. I'll change the link to point to the submission page.

**Comment by twhetzel** [comment]
Ok, linking back to the submission details page sounds good.
