### ISSUE TITLE
Extend the study template to capture Study Flag attributes during upload 

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwasdepo-deposition-service#151]
Extend the study template feature to capture Study Flag attributes during upload

**Comment by ala-ebi** [comment]
add 3 columns 'Sumstats', 'GxE' and 'Pooled' --- on header give description of each flag
each column would be preferred to be YES/NO  a dropdown on the template

**Comment by ljwh2** [comment]
Sumstats: Enter yes if summary statistics are available for this study 
GxE: Enter yes if the study is a GxE interaction analysis
Pooled: Enter yes if the study design uses pooled DNA from multiple individuals

**Comment by ljwh2** [comment]
Just a note that it should be efficient for the curator to enter flags of a publication (considering many studies per publication). So dropdown may not be the best approach if it necessitates a separate click per study (compared to copying down the text)

**Comment by ala-ebi** [comment]
@ljwh2 thanks. 

> to enter flags of a publication
did you mean flags for studies of a publication? because that's what I thought we're doing here.
also should those fields be mandatory? and for which templates? empty metadata, curator empty metadata, curator prefilled metadata, ss, curator ss,

**Comment by ljwh2** [comment]
> did you mean flags for studies of a publication? because that's what I thought we're doing here
Yes, sorry

**Comment by ljwh2** [comment]
I will discuss the questions with curators and get back to you

**Comment by ljwh2** [comment]
As discussed, the Sumstats flag should be a new management field for curators to use for prioritisation only. It should be populated with yes if the submission has sumstats, or also can be set manually. This field will not be represented in the curation DB. Curators currently get data from the curation DB for prioritisation, so will need to find a workaround during this interim time.

**Comment by ljwh2** [comment]
@ala-ebi see comments above
