### ISSUE TITLE
Deposition app to make the metadata templates for sumstats submission available to the sumstats service 

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwasdepo-deposition-service#175]
For summary statistics submissions only.

The validated metadata template needs to be available for the sumstats service to convert it into individual YAML files. The suggested approach is to drop the csv version(s) of the template into the globus directory that is available for that submission.

**Comment by jdhayhurst** [comment]
Will the template xls always be named the same (just in a different globus endpoint)? If not, you will need to send the sumstats service the file name, preferably in the PUT payload.

**Comment by sprintell** [comment]
@ala-ebi  to add authentication token to the endpoint

**Comment by ljwh2** [comment]
released and tested
