### ISSUE TITLE
When sumstats submissions have a value for "Analysis software", allow sumstats to validate true when p-values are zero

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwasdepo-deposition-service#231]
"Analysis software" is an optional field in the study template. If a value is given, when the POST request is made to the sumstats service to register (and validate) the sumstats files, add the analysis software field per study, `analysisSoftware: <sw name>`. By `analysisSoftware` field exists for the study, this tells the sumstats validator to allow p-values of 0, whereas by default these values are invalid.

Slides from discussion are here: 
https://docs.google.com/presentation/d/1ccWhl1GlU5hKi9yIXwLTdswJtOUsO2gI/edit?usp=sharing&ouid=115921420372247902258&rtpof=true&sd=true

**Comment by ljwh2** [comment]
Discuss and plan in this sprint

**Comment by karatugo** [comment]
GWAS sumstats service changes tested and merged to sandbox.

**Comment by karatugo** [comment]
- [ ] Test analysis software in sandbox

**Comment by karatugo** [comment]
Test okay with a template v1.11

**Comment by ljwh2** [comment]
curators to test

**Comment by earlEBI** [comment]
Tested with 2 sumstats-only submissions. Validation passes as long as something is entered in the analysis software column. 

The error message for sumstats files with 0 p-values and nothing entered in the analysis software column is unhelpful: 
“Errors: test_izzy2.tsv: Summary statistics file validation failed, please run the validator on your file to see the errors (available here: https://pypi.org/project/gwas-sumstats-tools/)”

Would it be possible to give a more helpful error message for this particular scenario, eg. "Error: Analysis software must be provided in the metadata template for summary statistics containing 0 p-values."

**Comment by karatugo** [comment]
Sure, let me see what I can do.

**Comment by karatugo** [comment]
Tested here. https://wwwdev.ebi.ac.uk/gwas/deposition/submission/667e92c52b46030001615a5d

**Comment by karatugo** [comment]
Inserted new error messages for zero p-values to sumstats-error collections of respective Mongo DB instances.

**Comment by earlEBI** [comment]
Tested with a sumstats-only submission - looks good to me!

**Comment by karatugo** [comment]
Thanks, deploying to prod

**Comment by ljwh2** [comment]
I think users might find the error message confusing: 

> Analysis software must be provided in the metadata template for summary statistics containing 0 p-values.

would be clearer as

> Analysis software must be provided in the metadata template for summary statistics containing p-values equal to zero.

**Comment by karatugo** [comment]
@karatugo roll back changes until java side is deployed

**Comment by karatugo** [comment]
Re-deployed v1.4.16.

**Comment by karatugo** [comment]
Updated the error message. It's ready to deploy when Java side is.
