### ISSUE TITLE
Create a workflow diagram for the Deposition System

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwasdepo-deposition-service#233]

**Comment by sajo-ebi** [comment]
THe workflow has been saved in the following google drive location

[https://drive.google.com/drive/u/0/folders/1KzZQNZDev8zEPHzaEiNoZ_gcPtaTRYGt](https://drive.google.com/drive/u/0/folders/1KzZQNZDev8zEPHzaEiNoZ_gcPtaTRYGt)
