### ISSUE TITLE
Deposition - Store Analysis software field in DB

### ISSUE THREAD

**Issue by sajo-ebi** [EBISPOT/gwasdepo-deposition-service#239]
Currently the metadata template contains Analysis software field which is not captured in DB , we need to store this in DB as this filed is required in Sumstats metadata Yml , this will need changes in Deposition service, template validator & Ingest service for metadata Yml API call.

**Comment by ljwh2** [comment]
@jiyue1214 to provide list of GCSTs and analysis software - this info was captured from old-style yaml files, not available in new-style ones

**Comment by jiyue1214** [comment]
GCST and available analysis_software: https://docs.google.com/spreadsheets/d/1sBdGFXZd2dZxIkO_BpDS44QV_Bqv2HWmmD6xDpQQrso/edit#gid=0

**Comment by ljwh2** [comment]
@sajo-ebi to discuss with @karatugo best approach to populate DB with analysis SW for these GCSTs

**Comment by ljwh2** [comment]
@sajo-ebi to create new ticket to populate old values and close this one

**Comment by sprintell** [comment]
This is now tracked here: https://github.com/EBISPOT/gwasdepo-deposition-service/issues/242

**Comment by jiyue1214** [comment]
I updated the analysis software I can acquire from all yaml files: 
7_Feb: I extracted analysis_software field from all yaml files before any regeneration on 7th Feb
30_Apr: I extract analysis_software field from all yaml files on the staging folder on 30th Apr

**Comment by jiyue1214** [comment]
Question: Do I need to check the user submission forms from Feb to Apr to see if any analysis_software is missing in the yaml file?
