### ISSUE TITLE
Deposition - Populate Old Studies  with Analysis Software values

### ISSUE THREAD

**Issue by sajo-ebi** [EBISPOT/gwasdepo-deposition-service#242]
As part of persisting Analysis software to DB , we also need to populate old values so that API can access the field, Yue to share the mapping sheet for old studies , need to write some utility script to copy using the mapping sheet to Mongo DB

**Comment by ljwh2** [comment]
@jiyue1214 just tagging you to provide information on analysis_software values to Sajo

**Comment by eks-ebi** [comment]
See spreadsheet link and further info in this ticket: Deposition - Store Analysis software field in DB

**Comment by sajo-ebi** [comment]
@jiyue1214 @earlEBI the analysis software has been updated for the attached sheet , there were few rows where Yue had update that it depends upon Biobank , @earlEBI request you to check those if needed we can update again

**Comment by sprintell** [comment]
@earlEBI  could you please help confirm this ?

**Comment by earlEBI** [comment]
Why does eg. GCST90296659 have no analysisSoftware populated in Mongo db?

**Comment by sajo-ebi** [comment]
@earlEBI the study 'GCST90296659' had two entries in DB one association to Metadata submission & other related to Sumstats submission, the query I ran was updating just one record, now I have updated the query to run for multiple entries for all studies , kindly confirm at your side.

**Comment by earlEBI** [comment]
ok I've checked a few and analysisSoftware is correctly populated in Mongo db.
