### ISSUE TITLE
Allow date embargo of prepublished submission

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/gwasdepo-deposition-service#3]
Submitter should have the ability to delay publication of their submission in the GWAS catalog by adding an embargo date to the submission. The embargo date would prevent the import of the submission into the catalog until the date specified. If the submission has a valid embargo date ,the submission would be put into an EMBARGOED status upon submission. The EMBARGOED state would prevent import until the state is set to SUBMITTED once the embargo date has passed.

**Comment by tudorgroza** [comment]
See: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/27
